name: Deploy to Google Cloud VM
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/apprentice-backend:${{ github.sha }}
      - name: Deploy to Google Cloud VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker stop apprentice-backend
            sudo docker rm apprentice-backend
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/apprentice-backend:${{ github.sha }}
            sudo docker run -d --name apprentice-backend -p 8080:4000 --env-file .env --restart always ${{ secrets.DOCKERHUB_USERNAME }}/apprentice-backend:${{ github.sha }}